version: '3'
services:
    php:
        build:
            context: ./
            dockerfile: ./etc/php/Dockerfile
        container_name: "php-fpm"
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes:
            - "./web:/var/www/html"
            - "./etc/php/php.ini:/usr/local/etc/php/php.ini"
            - "./etc/ssh:/root/.ssh/config.d"
    nginx:
        image: nginx:alpine
        container_name: "nginx"
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: unless-stopped
        depends_on:
            - php
            - mysqldb
    composer:
        image: "composer"
        container_name: "composer"
        volumes:
            - "./web:/app"
        command: install
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: unless-stopped
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: unless-stopped
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"